### PR TITLE
Fix parallelogram rotation

### PR DESCRIPTION
**Pull request by jespirit**
Fixes Issue #139 

Will have to do more testing though.

### CODE REVIEW

**Comment by PopeSpaceous** [comment]
Awesome Job!
I'll have to test this when I get a chance. 
I'll merge it after reviewing it.

**Comment by PopeSpaceous** [comment]
I've done some testing and the parallelogram is still flipping the same way. 
parallelflip1
parallelflip2

Also I noticed that the tangrams can't be completed when the parallelogram must be flipped.  See these two examples. 

tangramnotsolved
tangramnotsolved2

I tested those two on the previous version and they worked there. What I'm thinking is that its having an issue trying to figure out it's orientation. 

I would say, take a look at the code again and see what's happening. 
Thanks.

**Comment by PopeSpaceous** [comment]
I'm going to close the PR, Let me know when it's ready for more testing 👍

**Comment by lejara** [comment]
This pr does not need to be close, if he add new commits on his branch jespirit:fix-parallelogram-rotation, it will automatically show in the pr

**Comment by jespirit** [comment]
It seems to work now. I only tested easy puzzles.

I added the debug statements for easier testing. I can always remove them via rebase.

I won't explain how it works here. I wrote a blog post here for an in-depth explanation.

https://jespiritutech.wordpress.com/2018/11/24/parallelogram-rotation-fix/

**Comment by PopeSpaceous** [comment]
I'll take a look at it sometime this weekend. And i'll test the med, and hard tans too. 👍

**Comment by PopeSpaceous** [comment]
@jespirit I have played through the game. All the tangram puzzle can be completed with your code 👍 

The only thing I noticed that might be wrong is that the flip is doing as the pictures show (below). 
If this is how you think it should be we can keep it. Just let me know and I'll merge it. 
Thanks again for your hard work and sorry it took so long to test. 

tangram1
Tangram 2

**Comment by jespirit** [comment]
> @jespirit I have played through the game. All the tangram puzzle can be completed with your code 
> 
> The only thing I noticed that might be wrong is that the flip is doing as the pictures show (below).
> If this is how you think it should be we can keep it. Just let me know and I'll merge it.
> Thanks again for your hard work and sorry it took so long to test.
> 
> tangram1
> Tangram 2

Hmm, it *should* flip properly.

No worries. Last few weeks of school can be tough with projects, assignments, and exams.

I had anticipated some changes needed to be made for puzzles where the parallelogram was initially flipped. Hmm, that is interesting.

**Pull request merged**
